### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by Congee** [Rykka/colorv.vim#22]
<pre>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/CC/.vim/bundle/colorv.vim/autoload/colorv/colorv.py", line 229, in txt2hex
    for fm,reg in fmt.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'</pre>

if ```let g:colorv_has_python=0``` ,there's no error reported.
PS: My vim's compiled with python3.

**Comment by sashahart** [comment]
This can close due to PR #27.

**Comment by Congee** [comment]
Thanks for your code. :D
